spring:
  application:
    name: api-gateway
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://config-server:8888/}
  cloud:
    gateway:
      default-filters:
        - name: CircuitBreaker
          args:
            name: defaultCircuitBreaker
            fallbackUri: forward:/fallback
        - name: Retry
          args:
            retries: 1
            statuses: SERVICE_UNAVAILABLE
            methods: POST
      routes:
        - id: vets-service
          uri: lb://vets-service
          predicates:
            - Path=/api/vet/**
          filters:
            - StripPrefix=2
        - id: visits-service
          uri: lb://visits-service
          predicates:
            - Path=/api/visit/**
          filters:
            - StripPrefix=2
        - id: customers-service
          uri: lb://customers-service
          predicates:
            - Path=/api/customer/**
          filters:
            - StripPrefix=2
        - id: genai-service
          uri: lb://genai-service
          predicates:
            - Path=/api/genai/**
          filters:
            - StripPrefix=2
            - CircuitBreaker=name=genaiCircuitBreaker,fallbackUri=/fallback
---
spring:
  config:
    activate:
      on-profile: docker
    import: configserver:http://config-server:8888

logging:
  pattern:
    console: "%clr(%d{yyyy-MM-dd'T'HH:mm:ss.SSSXXX}){faint} %clr(%5p) %clr([%X{traceId:-},%X{spanId:-}]){cyan} %clr([%thread]){blue} %clr(%logger{36}){magenta} : %m%n%wEx"
    file: "%d{yyyy-MM-dd'T'HH:mm:ss.SSSXXX} %5p [%X{traceId:-},%X{spanId:-}] [%thread] %logger{36} - %msg%n"
  level:
    io.micrometer.tracing: DEBUG
    org.springframework.cloud.sleuth: DEBUG
    org.springframework.cloud.sleuth.autoconfig: DEBUG
    org.springframework.web: DEBUG
  charset:
    console: UTF-8
    file: UTF-8

management:
  tracing:
    sampling:
      probability: 1.0
